# DO NOT SET "required-players" BELOW 2!!!!
required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'MM'
  x: 2
  y: 69
  z: -4
  pitch: 0
  yaw: -180
arenas:
  '0':
    sign:
      world: 'World'
      x: 18
      y: 142
      z: 258
    spawn:
      world: 'MMarena1'
      x: 0
      y: 120
      z: 0
      pitch: 0
      yaw: -90
    game-spawn:
      world: 'MMarena1'
      x: 10
      y: 65
      z: 0
      pitch: 0
      yaw: -90
